version: '3'
services:
  prometheus:
    image: prom/prometheus:v2.2.0
    volumes:
      - ./monitor/prometheus.yml:/etc/prometheus/prometheus.yml
    links:
      - sample-micrometer-app
    ports:
      - "9090:9090"
      
  grafana:
    image: grafana/grafana:5.0.1
    volumes:
      - "./monitor/grafana-datasource.yml:/etc/grafana/provisioning/datasources/grafana-datasource.yml"
      - "./monitor/micrometer-demo-dashboard.json:/etc/grafana/dashboards/micrometer-demo-dashboard.json"
      - "./monitor/micrometer-latency.json:/etc/grafana/dashboards/default.json"
      - "./monitor/grafana-dashboard.yml:/etc/grafana/provisioning/dashboards/grafana-dashboard.yml"
    ports:
      - "3000:3000"
    depends_on:
      - prometheus      

  sample-micrometer-app:
    image: "bijukunjummen/sample-micrometer-app:0.0.1-SNAPSHOT"
    environment:
      SERVER_PORT: 8080
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8080:8080"
