kind: Service
apiVersion: v1
metadata:
  name: sample-micrometer-app-service
  labels:
    app: sample-micrometer-app-service
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: sample-micrometer-app