global:
  scrape_interval: 10s # By default, scrape targets every 15 seconds.
scrape_configs:
  - job_name: 'apps'
    scrape_interval: 5s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ["sample-micrometer-app:8080"]
